spring:
  application:
    name: transaction-processing-service
    id: 161
    entity-id: ADB
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/schedule_payment_db
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/liquibase-changelog.xml

jwt:
  enabled: true
  exclude-api-paths: /v3/api-docs.yaml,/swagger-ui,/actuator,/error,/v2,/swagger,/webjars
  default-membership-id: c9e3c400-640b-11ea-bc55-0242ac130003
  default-membership-role: SuperAdmin
  ignore-check: true
  header-name: X-JWT-Assertion
  providers:
    - issuer: wso2.org/products/am
      secret: lSGznpPgmBOY4rzD4dKV6yVt1zVdYkDNqciolbi4fRI=
      jwtUserType: APPLICATION_USER
      jwtAppType: APPLICATION
      expiry: 60
      verifySecret: false
      issuerClaim: iss
      userTypeClaim: http://wso2.org/claims/usertype
      userIdClaim: http://wso2.org/claims/userid
      orgIdClaim: http://wso2.org/claims/identity/organisationId
      entityIdClaim: http://wso2.org/claims/entityId
      appIdClaim: http://wso2.org/claims/applicationname
      roleClaim: http://wso2.org/claims/role
      permissionClaim: http://wso2.org/claims/permissions
      subscriberClaim: http://wso2.org/claims/subscriber
    - issuer: 101D
      secret: 2N+Pd5jwo/UXksl/EsDncl3Y7H0M7OQ/FzkvZ5o0MuM=
      jwtUserType: APPLICATION_USER
      jwtAppType: APPLICATION
      expiry: 60
      verifySecret: true
      issuerClaim: iss
      userTypeClaim: http://wso2.org/claims/usertype
      userIdClaim: http://wso2.org/claims/enduser
      orgIdClaim: http://wso2.org/claims/identity/organisationId
      entityIdClaim: http://wso2.org/claims/entityId
      appIdClaim: http://wso2.org/claims/applicationname
      roleClaim: http://wso2.org/claims/role
      permissionClaim: http://wso2.org/claims/permission
      subscriberClaim: http://wso2.org/claims/subscriber

logging.level:
  root: INFO
  io.marketplace: TRACE

pxchange:
  enabled: true
  entity-id: ADB

kafka:
  server: localhost:9092
  enabled: true
  brokers: localhost:9092
  group-id: ${spring.application.name}
  security:
    protocol: PLAINTEXT
  consumer:
    groupid: ${spring.application.name}

management.health.db.enabled: false
management.health.redis.enabled: false

# Cache config
cache:
  enabled: true

# Setting for Membership Service
membership.server.base-url: http://membership-service:8080


