spring:
  application:
    name: transaction-processing-service
    id: 161
    entity-id: ADB
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/transaction_processing_service_db
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/liquibase-changelog.xml
jwt:
  enabled: true
  exclude-api-paths: /
  ignore-check: false
  default-membership-id: test
  default-membership-role: test
  providers:
    - issuer: internal
      secret: 2N+Pd5jwo/UXksl/EsDncl3Y7H0M7OQ/FzkvZ5o0MuM=
      jwtUserType: APPLICATION_USER
      jwtAppType: APPLICATION
      expiry: 3600
      verifySecret: true
      issuerClaim: iss
      userTypeClaim: http://internal/claims/usertype
      userIdClaim: http://internal/claims/enduser
      orgIdClaim: http://internal/claims/identity/organisationId
      appIdClaim: http://internal/claims/applicationname
      roleClaim: http://internal/claims/role
      permissionClaim: http://internal/claims/permissions
      subscriberClaim: http://internal/claims/subscriber
logging.level:
  root: INFO
  io.marketplace: TRACE
pxchange:
  enabled: true
  entity-id: ADB
kafka:
  server: localhost:9092
  enabled: true
  brokers: localhost:9092
  group-id: ${spring.application.name}
  security:
    protocol: PLAINTEXT
  consumer:
    groupid: ${spring.application.name}
  topics:
    scheduled-payment-start: scheduled-payment-start
management.health.db.enabled: false
management.health.redis.enabled: false
# Cache config
cache:
  enabled: true
# Setting for Membership Service
membership.server.base-url: http://membership-service:8080
# Setting for Wallet Service
wallet.service.base-url: http://localhost:3001
# Setting for Account Opening Service
account-opening-service:
  base-url: http://localhost:9600
# Setting for Payment Service
payment-service:
  base-url: http://localhost:9400
  initiate-payment-endpoint: /payments
  confirm-payment-endpoint: /payments/{paymentId}
# Setting for Bank Information Service
bank-information-service:
  base-url: http://localhost:9300
  get-banks-endpoint: /banks
# Setting for sequence configuration
sequence-id-config:
  schedule-payment: 612dd073-6a35-416b-8739-5cde95bdc32a
  schedule-payment-item: 5dd9777a-5b6d-4fa9-b28c-6a002983a5b7
# Scheduled payment configuration
scheduled-payment-config:
  process-batch-size: 5
  accept-effective-date-from-job: false
  transaction-time-zone: Asia/Kuala_Lumpur
  dry-run-mode: false # dry run mode but not to process it.
# Mock Configuration
mock-config:
  enable-schedule-payment-mock-response: false
  enable-recurring-payment-mock-response: false
# Notification Async Configuration
notification:
  async:
    enabled: true
app-config:
  defaultPageNumber: 1
  defaultPageSize: 10
  server:
    timezone: UTC
# fnx payment notification configuration
fnx-payment:
  notification:
    limit-check-reject-template-name: payment-limit-check-reject
    insufficient-balance-reject-template-name: payment-insufficient-balance-reject
logging.level.org.apache.http.wire: TRACE

configuration:
  types: ROUNDUP_CONTRIBUTION
  logic-codes: DEFAULT