image:
  name: transaction-processing-service
  tag: <image-tag>
affinity: {}
kubernetes:
  imagePullPolicy: Always
  useSecrets: true
  imagePullSecrets: adbsecret
spring:
  cloud:
    config:
      enabled: true
      uri: http://configuration-service:8080/
      label: master
  liquibase:
    enabled: false
hpa:
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90
  minReplicas: 1
  maxReplicas: 3
datadog:
  enabled: false
  env: dev