name: Run sanitization checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  sanitize-checks:
    uses: 101digital/gh-actions/.github/workflows/sanitize-checks-java.yml@master
